### ISSUE TITLE
Hello, operate with circle?

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/announcementcenter#194] opened 2020-06-02 05:31 UTC
Is it possible to operate with circle?
Thank

**Comment by nickvergessen** [comment] 2020-06-03 10:32
I guess it would be possible.

But this app is currently in "maintenance only" mode. So unless someone makes a Pull Request it is unlikely to happen.

**Comment by nickvergessen** [comment] 2020-10-07 07:36
Duplicate of #89 89

**Closed by nickvergessen** 2020-10-07 07:36 UTC
Labels: 1. to develop, enhancement, feature: api ⚙️, feature: new form ➕
