### ISSUE TITLE
Cannot select last groups, if >25 groups exist. Make selection windows larger?

### ISSUE THREAD

**Issue by t-markmann** [nextcloud/announcementcenter#704] opened 2023-09-18 07:53 UTC
### Steps to reproduce
1. create about 25 to 30 Groups
![grafik](https://github.com/nextcloud/announcementcenter/assets/5323995/5d69a03b-6f79-4ee6-9499-832d6bcee7e3)

3. make a new announcement and try to select Groups >25

### Expected behaviour
I should be able to select every group.

### Actual behaviour
I cannot select the last groups.

When I first hover group selection:
![grafik](https://github.com/nextcloud/announcementcenter/assets/5323995/bdb89b53-0b47-4df3-9bd9-1b1c021165c3)

When I scroll down completely:
![grafik](https://github.com/nextcloud/announcementcenter/assets/5323995/03b29c6f-0ac6-4600-8041-61fad9548ce8)

Even if I type the first letters, I cannot select the last groups: 
![grafik](https://github.com/nextcloud/announcementcenter/assets/5323995/466701da-36a5-43e9-86c7-f15e5df10eef)

### Server configuration

**Operating system**:
Ubunu 20.04

**Web server:**
Apache

**Database:**
MySQL8 

**PHP version:**
8.0

**Nextcloud version:** (see Nextcloud admin page)
26.0.4

**Where did you install Nextcloud from:**
Zip

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 10

**Comment by nickvergessen** [comment] 2023-09-18 13:52
This should be fixed with v6.5.1 https://github.com/nextcloud/announcementcenter/issues/607#issuecomment-1449649067

**Comment by steve-boyle** [comment] 2023-10-05 16:23
I think the issue is here:
https://github.com/nextcloud/announcementcenter/blob/ed3a7c3698a13b0d3662209122566c97aa1dcd58/lib/Controller/APIController.php#L242

**Comment by thomaswennersten** [comment] 2023-10-17 06:29
I have the same problem, on the same version. Can this be fixed or is there a work around?

**Comment by nickvergessen** [comment] 2023-10-17 08:35
Adjust the line posted above to 250 for now.
I currently don't have too much time left over, but I hope to have it fixed in November

**Comment by evh-mh** [comment] 2023-12-21 06:19
Same issue here.
Annoucement Center: 6.7.0
NC: 27.1.3

**Comment by rawtaz** [comment] 2024-01-06 13:02
The fix for this problem is extremely simple, it's an at most three character change. Can someone with commit access please make the change, so we don't have to patch the code manually after every upgrade of the app? :)

**Comment by titi-81** [comment] 2024-03-08 09:01
Hi,

I've the same problem on version 6.7.0 of announcement center in Nextcloud.
The limit of number of groups seems already to be to 25 !
Is it a regression bug ?

I am new in github so I hope to follow the rules for presenting the bug.

How can I resolve the problem ?

Thanks a lot for your response.

**Comment by thomaswennersten** [comment] 2024-03-08 09:06
I think you can do the chnages yuerslf, check out  this link : https://github.com/nextcloud/announcementcenter/issues/704#issuecomment-1749258893

**Comment by titi-81** [comment] 2024-03-08 15:17
Thanks for your response, thomaswennersten

I am not used of Github : I understand I must clone the announcement center code, modify it at the specify line (replace 25 to 250 for exemple. But in nextcloud, how do I proceed for installing my version in substitution of the last pack application ? Is it a way to install a personal  version of the application by the admin interface of nextcloud or must I go directly on the server to perform the modification (but I don't control the server at this time) ?
Thank you for your patience if it's an evidence.

**Comment by thomaswennersten** [comment] 2024-03-08 15:48
I can not help you out I´m afraid since I have had help from an external consultant with this myslef.

**Comment by nickvergessen** [comment] 2024-03-08 16:01
> Is it a way to install a personal version of the application by the admin interface of nextcloud or must I go directly on the server to perform the modification (but I don't control the server at this time) ?

This would be required.

I forgot about this issue today again and just released 6.8.0 to be compatible with the next major version of Nextcloud.
I will schedule a reminder for next week again.

**Comment by rawtaz** [comment] 2024-03-08 16:37
@titi-81 How to manually apply the change depends on how you have Nextcloud installed and configured, so in your case it probably makes sense to wait for @nickvergessen to release a new version of the app which has the change in it already.

**Comment by titi-81** [comment] 2024-03-10 18:02
Thanks for all answers.

I hope the next release could repear this problem. Can I suggest a global parameter for this app that could be modified from administration parameters if it's possible. Thanks.

**Comment by titi-81** [comment] 2024-03-21 08:20
> > Is it a way to install a personal version of the application by the admin interface of nextcloud or must I go directly on the server to perform the modification (but I don't control the server at this time) ?
> 
> This would be required.
> 
> I forgot about this issue today again and just released 6.8.0 to be compatible with the next major version of Nextcloud. I will schedule a reminder for next week again.

Hi Joas,
Is there any news about this problem ?
Is there a new version to correct this limitation, please ?

Thanks

**Comment by nickvergessen** [comment] 2024-03-21 09:46
Waiting for feedback on https://github.com/nextcloud/announcementcenter/pull/767#issuecomment-2011749382
But plan to release it tomorrow

**Comment by nickvergessen** [comment] 2024-03-21 10:14
I found the actual bug now why search later didn't work...
Tested with 1k groups locally and works now. Will send a PR soon

**Closed** 2024-03-21 10:36 UTC

**Comment by nickvergessen** [comment] 2024-03-21 10:41
6.8.1 published to the appstore

**Comment by titi-81** [comment] 2024-03-22 07:55
Thanks a lot.

That's a pleasure to use your announcement center now with a full select group possibility.

Have a good day.
