### ISSUE TITLE
Include announcement text in e-mails

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/announcementcenter#115] opened 2018-09-18 19:37 UTC
When an announcement is set up with all the options enabled, the users get an e-mail telling them that there is an announcement.

My experience is that most users don't know what to do with this e-mail, as there is not even a link to the actual announcement. Further, notifications are often not read.

Including the announcement text directly in the e-mail is being sent would be nice. Only then real announcements, that are being read, are possible.

Maybe it would make sense to use a different app with the simple funcionallity to only send e-mails to all users or users of certain groups, without having all the options of the announcement center?

**Comment by nickvergessen** [comment] 2018-10-11 13:10
I just released 3.3.1 which brings at least the title of the announcements to the emails.
Also the title is clickable and leads to the announcement itself.

Do you think this is good enough?

**Comment by jancborchardt** [comment] 2018-10-23 12:35
Ideally, the full text of the announcement should be in the email. People don’t want to bother following a link just to read text. :slightly_smiling_face:

**Comment by nickvergessen** [comment] 2018-11-16 12:12
I see this as a duplicate of #65

**Closed by nickvergessen** 2018-11-16 12:12 UTC
Labels: design, enhancement, feature: notifications

**Comment by jancborchardt** [comment] 2019-01-04 16:39
@TomTurnschuh this issue was closed as a duplicate of https://github.com/nextcloud/announcementcenter/issues/65 – let’s continue there. :)

**Comment by TomTurnschuh** [comment] 2019-01-04 17:55
> 
> 
> @TomTurnschuh this issue was closed as a duplicate of #65 – let’s continue there. :)

Sure, I just wanted to give Joas an answer to his question in this thread. :)
