### ISSUE TITLE
Commenting is broken

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/announcementcenter#372] opened 2021-07-05 09:13 UTC
### Steps to reproduce
1. Open an announcement
2. Try to comment on it

### Expected behaviour
It should work.

### Actual behaviour
It fails.
![Screenshot 2021-07-05 at 11 13 03](https://user-images.githubusercontent.com/878997/124447762-fa03ba00-dd81-11eb-913a-628e93b41338.png)

**Request:**
```
URL: https://cloud.nextcloud.com/remote.php/dav/comments/announcement/166
Status: 404 Not Found
```

**Response:**
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Entity does not exist or is not available</s:message>
</d:error>

```

### Server configuration
c.nc.c

**Comment by nickvergessen** [comment] 2021-07-05 09:37
Duplicate of  #364

**Closed by nickvergessen** 2021-07-05 09:37 UTC
Labels: bug
