### ISSUE TITLE
Announcement center don't work with Chrome / Brave

### ISSUE THREAD

**Issue by D3nn7** [nextcloud/announcementcenter#307] opened 2021-03-11 09:03 UTC
### Steps to reproduce
1. post an announcement

### Expected behaviour
When you open the Announcement Center, all fields should be available and you should be able to create an announcement.

### Actual behaviour
The group selection is not displayed and the "Announce" or "Advanced options" button does not do anything. Only with Firefox it works.

### Server configuration

**Operating system**: 
Linux 4.19.0 x86_64

**Web server:**
Apache2

**Database:**
MYSQL 10.3.27

**PHP version:**
PHP 7.3.27

**Nextcloud version:**
20.0.8

**Where did you install Nextcloud from:**
Local

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
  - accessibility: 1.6.0  
  - activity: 2.13.4 
  - admin_audit: 1.10.0  
  - announcementcenter: 4.0.1  
  - bruteforcesettings: 2.0.1  
  - calendar: 2.1.3 
  - cloud_federation_api: 1.3.0  
  - comments: 1.10.0  
  - contacts: 3.4.3  
  - contactsinteraction: 1.1.0  
  - dashboard: 7.0.0  
  - data_request: 1.7.0 
  - dav: 1.16.2  
  - encryption: 2.8.1  
  - event_update_notification: 1.2.0  
  - external: 3.7.2  
  - federatedfilesharing: 1.10.2  
  - federation: 1.10.1 
  - files: 1.15.0  
  - files_frommail: 0.4.0  
  - files_pdfviewer: 2.0.1  
  - files_rightclick: 0.17.0  
  - files_sharing: 1.12.2  
  - files_trashbin: 1.10.1  
  - files_versions: 1.13.0  
  - files_videoplayer: 1.9.0  
  - forms: 2.1.0  
  - groupfolders: 8.2.0  
  - hsts: 0.8.0  
  - integration_github: 0.0.20  
  - logreader: 2.5.0  
  - lookup_server_connector: 1.8.0  
  - mail: 1.9.1  
  - maps: 0.1.8 
  - music: 1.0.3  
  - nextcloud_announcements: 1.9.0  
  - notes: 4.0.4  
  - notifications: 2.8.0  
  - oauth2: 1.8.0  
  - occweb: 0.0.7  
  - password_policy: 1.10.1  
  - photos: 1.2.3  
  - privacy: 1.4.0  
  - provisioning_api: 1.10.0  
  - recommendations: 0.8.0  
  - serverinfo: 1.10.0  
  - settings: 1.2.0  
  - sharebymail: 1.10.0  
  - side_menu: 1.23.1  
  - support: 1.3.0  
  - survey_client: 1.8.0  
  - suspicious_login: 3.2.1  
  - systemtags: 1.10.0  
  - tasks: 0.13.6  
  - text: 3.1.0  
  - theming: 1.11.0  
  - twofactor_backupcodes: 1.9.0  
  - updatenotification: 1.10.0  
  - user_status: 1.0.1  
  - viewer: 1.4.0  
  - weather_status: 1.0.0  
  - welcome: 0.0.5  
  - workflowengine: 2.2.0
 Disabled:  
 - files_external 
 - firstrunwizard  
 - user_ldap
```

**Nextcloud configuration:**

```
{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "cloud.slynite.com"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "dbtype": "mysql",        "version": "20.0.8.1",        "overwrite.cli.url": "https:\/\/cloud.slynite.com",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "oc_",        "mysql.utf8mb4": true,        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "app_install_overwrite": [            "admin_notifications",            "occweb",            "files_frommail"        ],        "maintenance": false,        "theme": "",        "loglevel": 2    }}
```

### Client configuration
**Browser:**
Brave, Chrome

**Operating system:**
Windows 10

#### Browser log
```
index.js:46 No OC found
t.getLanguage @ index.js:46
value @ gettext.js:45
(anonymous) @ l10n.js:3
(anonymous) @ main.js?v=861f0cd5-21:1
n @ bootstrap:19
(anonymous) @ main.js?v=861f0cd5-21:1
n @ bootstrap:19
(anonymous) @ main.js:1
(anonymous) @ main.js?v=861f0cd5-21:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js?v=861f0cd5-21:1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
o @ jquery.js:9789
0 @ jquery.js:26
n @ bootstrap:19
671 @ files_client.js?v=861f0cd5-21:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=861f0cd5-21:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
o @ jquery.js:9792
0 @ jquery.js:26
n @ bootstrap:19
671 @ files_client.js?v=861f0cd5-21:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=861f0cd5-21:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
mounted @ App.vue:117
Ue @ vue.runtime.esm.js:1854
Kt @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
w @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
Ln.$mount @ vue.runtime.esm.js:8415
e._init @ vue.runtime.esm.js:5018
Ln @ vue.runtime.esm.js:5085
(anonymous) @ main.js:37
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=861f0cd5-21:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
mounted @ App.vue:121
Ue @ vue.runtime.esm.js:1854
Kt @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
w @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
Ln.$mount @ vue.runtime.esm.js:8415
e._init @ vue.runtime.esm.js:5018
Ln @ vue.runtime.esm.js:5085
(anonymous) @ main.js:37
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=861f0cd5-21:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
mounted @ App.vue:121
Ue @ vue.runtime.esm.js:1854
Kt @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
w @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
Ln.$mount @ vue.runtime.esm.js:8415
e._init @ vue.runtime.esm.js:5018
Ln @ vue.runtime.esm.js:5085
(anonymous) @ main.js:37
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=861f0cd5-21:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script.js?v=861f0cd5-21:492
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ files.js?v=861f0cd5-21:122
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.caret.min.js?v=861f0cd5-21:2
(anonymous) @ jquery.caret.min.js?v=861f0cd5-21:2
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.atwho.min.js?v=861f0cd5-21:1
(anonymous) @ jquery.atwho.min.js?v=861f0cd5-21:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script.js?v=861f0cd5-21:417
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
init @ script.js?v=861f0cd5-21:39
(anonymous) @ script.js?v=861f0cd5-21:418
l @ jquery.js:3187
add @ jquery.js:3246
m.fn.ready @ jquery.js:3496
(anonymous) @ script.js?v=861f0cd5-21:417
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
init @ script.js?v=861f0cd5-21:40
(anonymous) @ script.js?v=861f0cd5-21:418
l @ jquery.js:3187
add @ jquery.js:3246
m.fn.ready @ jquery.js:3496
(anonymous) @ script.js?v=861f0cd5-21:417
script.js?v=861f0cd5-21:42 Uncaught TypeError: OCA.AnnouncementCenter.Comments.CommentsTabView is not a constructor
    at Object.init (script.js?v=861f0cd5-21:42)
    at HTMLDocument.<anonymous> (script.js?v=861f0cd5-21:418)
    at l (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at e.fn.init.m.fn.ready (jquery.js:3496)
    at script.js?v=861f0cd5-21:417
init @ script.js?v=861f0cd5-21:42
(anonymous) @ script.js?v=861f0cd5-21:418
l @ jquery.js:3187
add @ jquery.js:3246
m.fn.ready @ jquery.js:3496
(anonymous) @ script.js?v=861f0cd5-21:417
globals.js:60 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ templates.js?v=861f0cd5-21:2
(anonymous) @ templates.js?v=861f0cd5-21:185
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:2
(anonymous) @ script?v=2:179
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:3
(anonymous) @ script?v=2:179
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:4
(anonymous) @ script?v=2:179
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:5
(anonymous) @ script?v=2:179
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:6
(anonymous) @ script?v=2:179
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:86
(anonymous) @ script?v=2:179
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:87
(anonymous) @ script?v=2:179
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:94
(anonymous) @ script?v=2:179
session-heartbeat.js:97 session heartbeat polling started
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
(anonymous) @ sideMenu.js?v=861f0cd5-21:24
n @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:21
dispatch @ jquery.js:4737
v.handle @ jquery.js:4549
trigger @ jquery.js:7807
e.event.trigger @ jquery-migrate.min.js:2
(anonymous) @ jquery.js:7875
each @ jquery.js:365
each @ jquery.js:137
trigger @ jquery.js:7874
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
(anonymous) @ sideMenu.js?v=861f0cd5-21:24
n @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:23
dispatch @ jquery.js:4737
v.handle @ jquery.js:4549
trigger @ jquery.js:7807
e.event.trigger @ jquery-migrate.min.js:2
(anonymous) @ jquery.js:7875
each @ jquery.js:365
each @ jquery.js:137
trigger @ jquery.js:7874
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
(anonymous) @ sideMenu.js?v=861f0cd5-21:24
n @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:24
dispatch @ jquery.js:4737
v.handle @ jquery.js:4549
trigger @ jquery.js:7807
e.event.trigger @ jquery-migrate.min.js:2
(anonymous) @ jquery.js:7875
each @ jquery.js:365
each @ jquery.js:137
trigger @ jquery.js:7874
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
(anonymous) @ sideMenu.js?v=861f0cd5-21:24
n @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ script?v=2:71
dispatch @ jquery.js:4737
v.handle @ jquery.js:4549
trigger @ jquery.js:7807
e.event.trigger @ jquery-migrate.min.js:2
(anonymous) @ jquery.js:7875
each @ jquery.js:365
each @ jquery.js:137
trigger @ jquery.js:7874
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
(anonymous) @ sideMenu.js?v=861f0cd5-21:24
n @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
displayEncryptionWarning @ encryption.js?v=861f0cd5-21:18
(anonymous) @ encryption.js?v=861f0cd5-21:32
(anonymous) @ delay.js:7
setTimeout (async)
(anonymous) @ delay.js:6
(anonymous) @ restArguments.js:18
He @ _executeBound.js:8
i @ partial.js:18
(anonymous) @ encryption.js?v=861f0cd5-21:31
4globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
alwaysDisplayed @ script?v=2:132
setTimeout (async)
(anonymous) @ script?v=2:177
(anonymous) @ script?v=2:179
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ sideMenu.js?v=861f0cd5-21:7
setTimeout (async)
retrieveApps @ sideMenu.js?v=861f0cd5-21:7
mounted @ sideMenu.js?v=861f0cd5-21:7
He @ sideMenu.js?v=861f0cd5-21:7
Yt @ sideMenu.js?v=861f0cd5-21:7
e @ sideMenu.js?v=861f0cd5-21:7
xn.$mount @ sideMenu.js?v=861f0cd5-21:7
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
setTimeout (async)
g @ sideMenu.js?v=861f0cd5-21:24
(anonymous) @ sideMenu.js?v=861f0cd5-21:24
n @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
(anonymous) @ sideMenu.js?v=861f0cd5-21:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
get @ globals.js:91
(anonymous) @ sideMenu.js?v=861f0cd5-21:7
setTimeout (async)
retrieveApps @ sideMenu.js?v=861f0cd5-21:7
attributes (async)
Ye @ jquery.js:5665
get @ jquery.js:6214
css @ jquery.js:6183
(anonymous) @ jquery.js:9726
I @ jquery.js:3643
m.each.m.each.m.fn.<computed> @ jquery.js:9699
ae @ init.js:49
setTimeout (async)
se @ init.js:203
(anonymous) @ main.js:37
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
![Capture](https://user-images.githubusercontent.com/79147263/110762305-eec7d400-8250-11eb-8ae6-b131014b32b0.PNG)

```

**Comment by nickvergessen** [comment] 2021-03-11 09:19
Duplicate of #252

**Closed** 2021-03-11 09:20 UTC
