### ISSUE TITLE
Group selection shows only [object Object] so groups cant be selected in nextcloud 25 and announcement center 6.5.0

### ISSUE THREAD

**Issue by thomasosche** [nextcloud/announcementcenter#613] opened 2023-03-01 06:38 UTC
### Steps to reproduce
1.anouncemet center 6.4.0 worked well on nexcloud 25 incl group selection in the post form
2.after update to 6.5.0 group selection does not work - only [object Object] is shown for each group and cant be selected

### Expected behaviour
group selection should work in announcement post form

### Actual behaviour
only [object Object] is shown for each group is shown

### Server configuration

**Operating system**:

**Web server:**

**Database:** mysql 10.5

**PHP version:** 8.0

**Nextcloud version:** (see Nextcloud admin page) 25.0.3

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```No errors have been found.

**List of activated apps:**
![image](https://user-images.githubusercontent.com/114228172/222063312-af4da1e0-7a70-40b1-b240-0218170fde69.png)

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

### Logs

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment] 2023-03-01 07:22
Duplicate of #607

**Closed** 2023-03-01 07:22 UTC
