### ISSUE TITLE
The annoucements sent to groups are not notiffied to users

### ISSUE THREAD

**Issue by rodrigoabella** [nextcloud/announcementcenter#184] opened 2020-03-28 23:42 UTC
### Steps to reproduce
1. post an announcement to groups
2. run the cron job to announce the announcement

### Expected behaviour
The annoucement is notified, shown and received in notification panel or in the mobile app for all users belongs to the group

### Actual behaviour
The announcement  is not shown and it doesn't show in the notification panel for all users belongs to the group
The announcemnet is shown in the activity tab/view
### Server configuration

**Operating system**:
Ubuntu 18.04

**Database:**
SQLite

**Announcement center version:**
3.7.0

**Nextcloud announcements version:**
1.7.0

**Nextcloud version:**
Nextcloud 18.0.2

**Where did you install Nextcloud from:**
local with Docker

**List of activated apps:**

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - announcementcenter: 3.7.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.5
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - forms: 1.1.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ojsxc: 3.4.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quicknotes: 0.2.3
  - recommendations: 0.6.0
  - richdocuments: 3.5.2
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - sociallogin: 2.4.5
  - spreed: 8.0.5
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - admin_notifications
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080",
            "192.168.254.*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "18.0.2.2",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "installed": true,
        "app_install_overwrite": [
            "ojsxc",
            "admin_notifications"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by rodrigoabella** [comment] 2020-04-02 23:20
Hi @nickvergessen, could you see this issue?
Do you know something abaut https://help.nextcloud.com/t/some-workflows-are-unavailable-for-me/76267?

Thanks a lot!

**Comment by nickvergessen** [comment] 2020-04-03 08:04
Sorry, I don't have a lot of time available these days as I'm also in charge of Nextcloud Talk (which is highly demanded in the current days)

**Comment by gibelium** [comment] 2020-04-16 10:22
Announcements to all users (e.g. blank groups field) also do not generate any notifications.

**Comment by nickvergessen** [comment] 2020-04-16 11:20
> Announcements to all users (e.g. blank groups field) also do not generate any notifications.

Then your cron job is not executed correctly.

**Comment by gibelium** [comment] 2020-04-17 11:56
Background Jobs are handle via `Webcron` in my Nextcoud instance. To change it to use `Cron` I would have to ask my hoster if this is possible.

Do I have to change the cron job configuration to activate notifications for announcements?
How can I check whether the cron jobs are successfully executed?

**Comment by SLYtiger16** [comment] 2020-04-24 23:13
I can confirm this behavior as well. I use `cron` job and only announcements to 'Everyone', made exclusively by system admins have notifications to users.

**Comment by SLYtiger16** [comment] 2020-06-15 22:35
Has there been any movement on this?

**Comment by tinsjourney** [comment] 2020-10-14 15:46
I have the same problem with : 

- Nextcloud : 20.0.0
- Announcement center : 4.0.0

Announcement to everyone work
Announcement to group failed

**Comment by nickvergessen** [comment] 2021-01-27 00:02
I just tested this with the upcoming 5.0 for Nextcloud 21 and it works fine.
However note that it only works for users which logged in before.

**Comment by lvarnava** [comment] 2021-07-24 12:32
I have the same problem with :

Nextcloud : 21.0.3
Announcement center : 5.0.0
Announcement to everyone work
Announcement to group failed

**Comment by scriptsagency** [comment] 2021-09-22 10:25
I discovered a scenario which could be related to this issue: 

Steps:
- Create "announcement1" which should be notified to the users in Group1. 
- Immediately create "announcement2" which should be notified to the users in the same Group1. 
- Run the cron or wait for the cron job to run the BackgroundJob and users in Group1 will only see the "announcement1" 

Here the problem is the variable protected $notifiedUsers = []; from lib/BackgroundJob.php
Solution  is to update BackgroundJob.php :
L120 add:  $this->notifiedUsers = []; 

This will reset the notifiedUsers for every cron job run and in the same time it will allow to notify a user only once for one announcement. 

@nickvergessen I've tried to push a new branch with this change and start a PR since it is a clear bug for this edge case, but I don't have the rights to do so.

**Comment by nickvergessen** [comment] 2021-09-22 10:36
Invited you to the org. Accept the invite and you should be able to push a branch

**Comment by nickvergessen** [comment] 2021-09-22 10:44
You are right, now after trying it shows that the BackgroundJob object is reused and not a new one for each execution.

**Comment by nickvergessen** [comment] 2021-09-22 10:49
To make it cleaner we could also move all logic out of the BackgroundJob class into a service and that then clears the array at the end of the job

**Comment by nickvergessen** [comment] 2021-09-22 12:31
Fixed by #394

**Closed by nickvergessen** 2021-09-22 12:31 UTC
Labels: bug, needs info, 1. to develop, feature: notifications 🔔
